apiVersion: kubernetes.vultr.upbound.io/v1alpha1
kind: NodePools
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/nodepools
  labels:
    testing.upbound.io/example-name: np-1
  name: np-1
spec:
  forProvider:
    autoScaler: true
    clusterId: ${vultr_kubernetes.k8.id}
    label: my-label
    labels:
      my-label: a-label-on-all-nodes
      my-second-label: another-label-on-all-nodes
    maxNodes: 2
    minNodes: 1
    nodeQuantity: 1
    plan: vc2-4c-8gb
    tag: my-tag
    taints:
    - effect: NoExecute
      key: a-taint
      value: is-tainted
    - effect: NoSchedule
      key: another-taint
      value: is-tainted
    userData: ${base64encode("This will be added to node user data")}
